### ISSUE TITLE
java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by nickzam** [xsc/minion#1]
If port is used by another app/nrepl minion generates exception (see title) and exits. 
May be it would be better to try to find next free port for minion's nrepl to continue operation?

**Comment by xsc** [comment]
@nickzam The REPL port is supposed to be set explicitly, either using `:default-port` in `defmain`, the `--repl-port` command line switch or `:repl-port` option map entry. If you want to have multiple instances of your application running, you have to explicitly tell them which port to choose.

I'll look into the possibility of having port ranges/multiple ports in `defmain`, though, i.e.:

``` clojure
(defmain -main
  :default-port [1234 1235 1236]
  ...)
```

And the first free one could be chosen. Alternatively, setting the value to `:any` could prompt your desired behaviour. I'll report back once there is movement.
